version: '2'
services:

  openresty:
    image: openresty/openresty:jessie
    command: [nginx-debug, '-g', 'daemon off;']
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./index.html:/etc/nginx/html/index.html
